# Generated by Django 6.1 on 2026-08-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
