# Generated by Django 6.0.6 on 2026-08-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(blank=True, choices=[('sistemas', 'Sistemas'), ('analisis', 'Analisis'), ('engineering', 'Engineering'), ('economia', 'Economia'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Opcional — imagen de portada para el post.', null=True, upload_to='blog/imagenes/%Y/%m/', verbose_name='Imagen'),
        ),
    ]
